# Generated by Django 5.0.6 on 2024-06-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SMALL', 'small'), ('LARGE', 'large'), ('MEDIUM', 'medium'), ('EXTRA_LARGE', 'extra_large')], default='SMALL', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=30)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
